In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensor

### Creating tensors

In [9]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get Tensor back as INT
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Tensor
TENSOR = torch.tensor([[[[1, 2, 3],
                         [4,5,6],
                         [7,8,9],
                         [10,11,12]],
                        [[1, 2, 3],
                         [4,5,6],
                         [7,8,9],
                         [10,11,12]]
                        ]])
TENSOR



tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]],

         [[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])

In [20]:
TENSOR

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]],

         [[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])

In [21]:
TENSOR.shape

torch.Size([1, 2, 4, 3])

### Random Tensors

Why random Tensors?

Random Tensors are important, because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [22]:
# Create a Random Tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3894, 0.4331, 0.3125, 0.0955],
        [0.1991, 0.7117, 0.8011, 0.3376],
        [0.9060, 0.2597, 0.3905, 0.3405]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor_image = torch.rand(size=(3, 224, 224)) # Color Channel, Height, Width
random_tensor_image.ndim, random_tensor_image.shape

(3, torch.Size([3, 224, 224]))

## Zeros and Ones

In [25]:
# Create a Tensor with all Zeros
tensor_zero = torch.zeros(size=(3, 4))
tensor_zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a Tensor with all Ones
tensor_one = torch.ones(3, 4)
tensor_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
tensor_one.dtype

torch.float32

### Create Range of Tensors and tensors-like

In [28]:
ten = torch.arange(start=0, end=11, step=1)
ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
ten_zeros = torch.zeros_like(input=ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note** Tensor Datatypes is one of the 3 big error you'll run into PyTorch and DL:

1. Tensors not right Datatypes
2. Tensors not right Shape
3. Tensors not on right Device

In [30]:
# Float32 Tensor
float_32_tensor = torch.tensor([3.0, 5.0, 7.0],
                               dtype=torch.int, # What Datatype
                               device=None, # What Device is your tensor on (CPU, GPU, ect.)
                               requires_grad=False # Whether or not to track gradiens with this tensors operations
                               )
float_32_tensor

tensor([3, 5, 7], dtype=torch.int32)

In [31]:
float_32_tensor.dtype

torch.int32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 5., 7.], dtype=torch.float16)

In [33]:
float_32_tensor * float_16_tensor

tensor([ 9., 25., 49.], dtype=torch.float16)

In [34]:
# Create Tensor
myTensor = torch.rand(3, 4)

print(myTensor)

print(f"Datatype of Tensor {myTensor.dtype}")
print(f"Device of Tensor {myTensor.device}")
print(f"Shape of Tensor {myTensor.shape}")

tensor([[0.8918, 0.8768, 0.9732, 0.6265],
        [0.8328, 0.1106, 0.0318, 0.3861],
        [0.4214, 0.6414, 0.5326, 0.3338]])
Datatype of Tensor torch.float32
Device of Tensor cpu
Shape of Tensor torch.Size([3, 4])


### Manipulating Tensors (Tensor Operations)

Tensor Operations include:
* Addiditon
* Subtraciton
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [35]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [36]:
tensor * 10


tensor([10, 20, 30])

In [37]:
tensor - 10

tensor([-9, -8, -7])

### Matrix Multiplication

Two main ways of Performing a Multiplication in DL and Neural Networks

1. Element Wise Multiplication -> Tensor x 3
2. Matrix Multiplication (Dot Product)


In [38]:
# Element Wise
print(tensor, "*", tensor)
print(f"Equals {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [39]:
# Matrix Multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.84 ms, sys: 0 ns, total: 1.84 ms
Wall time: 10.8 ms


tensor(14)

In [40]:
# Matrix Multiplication by Hand
1 * 1 + 2 * 2 + 3 * 3

14

In [41]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.16 ms, sys: 67 µs, total: 2.22 ms
Wall time: 3.51 ms


There are two main Rules that performing matrix multiplication needs to satisfy:
1. The **inner Dimensions** must match:
* `(2, 3) @ (2, 3)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The Resulting matrix has the shape of the **outer Dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [42]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 2))

tensor([[1.7111, 1.4303],
        [1.5500, 1.5704],
        [0.3062, 0.3476]])

### One of the most common errors in DL: Shape Errors

In [43]:
tensor_A = torch.tensor([[1 ,2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix the Error we can Transpose it (Turning it around)
To do this use the .T.
By Example: torch.matmul(tensor_A, tensor_B.T)

In [44]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean and sum of tensors (Tensor aggregation)

In [45]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
x.min(), torch.min(x), min(x)

(tensor(0), tensor(0), tensor(0))

In [47]:
x.max()

tensor(90)

In [48]:
# You only can call mean() if the tensor is in float32
x.type(torch.float32).mean()

tensor(45.)

In [49]:
x.sum()

tensor(450)

## Reshaping, viewing and stacking
* Reshaping - reshapes an input tensor to a defined shape
* View - Return the view of an input tensor of certain shape but keep the same memory as the original Tensor
* Stacking - Combine multiple Tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [50]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Adding a extra dimension
x_reshaped = x.reshape(1, 9) # Number Mulitplied must give the torch.Size
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [52]:
# Change the View
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Changing z changes x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
# Stack Tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# Squeeze
squeeze = torch.tensor([[[[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]]]])
squeeze.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
squeeze.unsqueeze(dim=3)

tensor([[[[[1, 2, 3]],

          [[4, 5, 6]],

          [[7, 8, 9]]]]])

In [57]:
# Permute - rearanges the order of a Tensor
per = torch.rand(size=(2, 2, 3))

permuted_ten = per.permute(2, 0, 1)
print(per.shape)
print(permuted_ten.shape)

torch.Size([2, 2, 3])
torch.Size([3, 2, 2])


## Indexing

In [58]:
j = torch.arange(1, 10).reshape(1, 3, 3)
j, j.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Let's index on our tensor
j[0, 1, 1]

tensor(5)

## PyTorch Tensors & NumPy

NumPy is a popular scientific PYthon Numerical Computing Library

And because of this PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.tensor.numpy()`

In [60]:
# NumPy Array to Tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
# Tensor to NumPy Array
ten = torch.ones(9)
arr = ten.numpy()
arr, ten

(array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]))

## Reproducibility (Trying to take the Random out of the Random)

In short how a Neural Network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better repressentations of the data -> again -> again -> again...`

To reduce the randomness in Neural Networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "falvour" the randomness

In [62]:
## Create Random Tensors

randomA = torch.rand(3, 4)
randomB = torch.rand(3, 4)

print(randomA)
print(randomB)
print(randomA == randomB)

tensor([[0.9850, 0.3322, 0.8356, 0.6122],
        [0.8813, 0.2221, 0.7558, 0.0660],
        [0.6359, 0.0193, 0.0174, 0.6096]])
tensor([[0.7969, 0.2587, 0.3171, 0.8079],
        [0.2133, 0.8973, 0.6930, 0.7414],
        [0.2891, 0.4567, 0.4444, 0.3225]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [63]:
# Let's make some random but reproducible tensors

#  SEt the random seed
randomseed = 42
torch.manual_seed(randomseed)

randomC = torch.rand(3, 4)
torch.manual_seed(randomseed)
randomD = torch.rand(3, 4)

print(randomC)
print(randomD)
print(randomC == randomD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA Hardware + PyTorch working behind the scenes to make everything good (hunky dory)

### Getting GPU

1. Easiest - Use Google Colab for Free GPU (options to upgrade)
2. Use your own GPU - takes a little bit of setup and requires the investment of buying a GPU, there is a lot of options...
3. Use Cloud computing - GCP, Azure, AWS

2, 3 needs a little bit of setting up

In [64]:
!nvidia-smi

Thu Mar 28 19:54:32 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access with PyTorch

In [65]:
# Check for GPU access for PyTorch
torch.cuda.is_available()

True

In [66]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [67]:
# Count number of devices
torch.cuda.device_count()

1

## Putting Tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [70]:
# Create Tensor (Default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [73]:
# Move tensor to GPU if avaliable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to CPU

In [76]:
  # If tensor is on GPU, can't transform it to NumPy
  tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [77]:
# To fix it, we can first set it to the CPU
tensor_back_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_cpu

array([1, 2, 3])